// <auto-generated />
using System;
using FincApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FincApp.Infrastructure.Migrations
{
    [DbContext(typeof(FincAppDbContext))]
    partial class FincAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "production_type", "production_type", new[] { "cattle", "swine", "poultry" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "admin", "worker" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FincApp.Core.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("IdentificationTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identification_tag");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("healthy")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("production_type")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("idx_animals_farm");

                    b.HasIndex("FarmId", "IdentificationTag")
                        .IsUnique()
                        .HasDatabaseName("uq_farm_animal_tag");

                    b.ToTable("animals", (string)null);
                });

            modelBuilder.Entity("FincApp.Core.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_farms_owner");

                    b.ToTable("farms", (string)null);
                });

            modelBuilder.Entity("FincApp.Core.FarmAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("UserId", "FarmId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_farm_assignment");

                    b.ToTable("farm_assignments", (string)null);
                });

            modelBuilder.Entity("FincApp.Core.HealthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("diagnosis");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SymptomsDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symptoms_description");

                    b.Property<string>("TreatmentAdministered")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("treatment_administered");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("idx_health_animal");

                    b.ToTable("health_records", (string)null);
                });

            modelBuilder.Entity("FincApp.Core.ProductionModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Type")
                        .HasColumnType("production_type")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "Type")
                        .IsUnique()
                        .HasDatabaseName("idx_modules_farm_type");

                    b.ToTable("production_modules", (string)null);
                });

            modelBuilder.Entity("FincApp.Core.SyncTelemetryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DeviceUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<int>("RowsSynced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rows_synced");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SynchronizedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synchronized_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("idx_sync_telemetry_farm");

                    b.HasIndex("UserId");

                    b.ToTable("sync_telemetry_logs", (string)null);
                });

            modelBuilder.Entity("FincApp.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("user_role")
                        .HasDefaultValue(1)
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FincApp.Core.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("log_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("idx_weight_animal");

                    b.ToTable("weight_logs", (string)null);
                });

            modelBuilder.Entity("FincApp.Core.Animal", b =>
                {
                    b.HasOne("FincApp.Core.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animal_farm");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FincApp.Core.Farm", b =>
                {
                    b.HasOne("FincApp.Core.User", "Owner")
                        .WithMany("OwnedFarms")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_farm_owner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FincApp.Core.FarmAssignment", b =>
                {
                    b.HasOne("FincApp.Core.Farm", "Farm")
                        .WithMany("Assignments")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_farm");

                    b.HasOne("FincApp.Core.User", "User")
                        .WithMany("Assignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_user");

                    b.Navigation("Farm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FincApp.Core.HealthRecord", b =>
                {
                    b.HasOne("FincApp.Core.Animal", "Animal")
                        .WithMany("HealthRecords")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_animal");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("FincApp.Core.ProductionModule", b =>
                {
                    b.HasOne("FincApp.Core.Farm", "Farm")
                        .WithMany("ProductionModules")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_farm");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FincApp.Core.SyncTelemetryLog", b =>
                {
                    b.HasOne("FincApp.Core.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_farm");

                    b.HasOne("FincApp.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sync_user");

                    b.Navigation("Farm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FincApp.Core.WeightLog", b =>
                {
                    b.HasOne("FincApp.Core.Animal", "Animal")
                        .WithMany("WeightLogs")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weight_animal");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("FincApp.Core.Animal", b =>
                {
                    b.Navigation("HealthRecords");

                    b.Navigation("WeightLogs");
                });

            modelBuilder.Entity("FincApp.Core.Farm", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ProductionModules");
                });

            modelBuilder.Entity("FincApp.Core.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("OwnedFarms");
                });
#pragma warning restore 612, 618
        }
    }
}
