package com.irwi.fincapp.repository;
import android.content.*;import android.database.*;import android.database.sqlite.SQLiteDatabase;import com.irwi.fincapp.database.DatabaseHelper;import java.text.SimpleDateFormat;import java.util.*;
public class AnimalRepository{
 private final DatabaseHelper h; public AnimalRepository(Context c){h=new DatabaseHelper(c);} private String now(){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss",Locale.US).format(new Date());}
 public long addAnimal(String farmId,String type,String tag,String birth){SQLiteDatabase db=h.getWritableDatabase();ContentValues v=new ContentValues();v.put("cloud_id",UUID.randomUUID().toString());v.put("farm_cloud_id",farmId);v.put("type",type);v.put("identification_tag",tag);v.put("birth_date",birth);v.put("status","active");v.put("created_at",now());v.put("sync_status","pending");long id=db.insert("animals",null,v);queue("animals",id,"create");return id;}
 public void addWeight(long animalId,double kg){SQLiteDatabase db=h.getWritableDatabase();String cloud=getAnimalCloud(animalId);ContentValues v=new ContentValues();v.put("cloud_id",UUID.randomUUID().toString());v.put("animal_id",animalId);v.put("animal_cloud_id",cloud);v.put("weight_kg",kg);v.put("log_date",now());v.put("sync_status","pending");long id=db.insert("weight_logs",null,v);queue("weight_logs",id,"create");}
 public void addHealth(long animalId,String symptoms,String diagnosis,String treatment){SQLiteDatabase db=h.getWritableDatabase();String cloud=getAnimalCloud(animalId);ContentValues v=new ContentValues();v.put("cloud_id",UUID.randomUUID().toString());v.put("animal_id",animalId);v.put("animal_cloud_id",cloud);v.put("symptoms_description",symptoms);v.put("diagnosis",diagnosis);v.put("treatment_administered",treatment);v.put("recorded_at",now());v.put("sync_status","pending");long id=db.insert("health_records",null,v);queue("health_records",id,"create");}
 private void queue(String e,long id,String op){SQLiteDatabase db=h.getWritableDatabase();ContentValues v=new ContentValues();v.put("entity_name",e);v.put("entity_id",id);v.put("operation_type",op);v.put("payload","");v.put("sync_status","pending");v.put("created_at",now());db.insert("sync_queue",null,v);} 
 public Cursor animals(){return h.getReadableDatabase().rawQuery("SELECT id, identification_tag, type, sync_status FROM animals ORDER BY id DESC",null);} 
 public String getAnimalCloud(long id){Cursor c=h.getReadableDatabase().rawQuery("SELECT cloud_id FROM animals WHERE id=?",new String[]{String.valueOf(id)});try{return c.moveToFirst()?c.getString(0):null;}finally{c.close();}}
 public int pendingCount(){Cursor c=h.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM sync_queue WHERE sync_status='pending'",null);try{return c.moveToFirst()?c.getInt(0):0;}finally{c.close();}}
}
